### ISSUE TITLE
Feature request: buffer as input/output

### ISSUE THREAD

**Issue by thgh** [ogunsoladebayo/omni-cloud#12]
Hi, awesome project with minimal footprint!

Would you consider adding support for stream or buffer so the files don't have to hit the filesystem?

**Comment by ogunsoladebayo** [comment]
I agree, this would be nice to have. I'll see if I can implement this in my free time

**Comment by ogunsoladebayo** [comment]
Closing this issue as this feature has been added and the docs updated.

**Comment by thgh** [comment]
Sweet 💯
